/**
 * Marketplace Fitness — Database seed
 *
 * Reads the JSON files in /data/products/ (one per category, generated by
 * the research-agent run) and seeds Brands, Products, and Trainers.
 *
 * Run with: `npm run db:seed`  (which calls `tsx prisma/seed.ts`)
 */
import path from "node:path";
import fs from "node:fs";
import { PrismaClient } from "../src/generated/prisma/client.ts";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";

// Prisma 7 + DATABASE_URL="file:./dev.db" creates the DB at project root.
const dbPath = path.join(process.cwd(), "dev.db");
const adapter = new PrismaBetterSqlite3({ url: dbPath });
const prisma = new PrismaClient({ adapter });

type SeedProduct = {
  name: string;
  slug: string;
  brand: string;
  category: string;
  priceMrp: number;
  priceSale: number;
  description: string;
  rating: number;
  reviewCount: number;
  stock: number;
  isBestseller: boolean;
  isSellingFast: boolean;
  proteinPerServing?: string;
  servingsPerContainer?: number;
  dosePerServing?: string;
  capsules?: number;
  tablets?: number;
  caloriesPerServing?: number;
};

const CATEGORY_FILES = [
  "whey-protein.json",
  "creatine.json",
  "fat-burner.json",
  "mass-gainer.json",
  "multivitamin.json",
];

function loadProducts(): SeedProduct[] {
  const dataDir = path.join(process.cwd(), "data", "products");
  return CATEGORY_FILES.flatMap((file) => {
    const full = path.join(dataDir, file);
    const raw = fs.readFileSync(full, "utf-8");
    return JSON.parse(raw) as SeedProduct[];
  });
}

function generateTrainerCode(): string {
  // TRN-XXXXXX with uppercase letters + digits
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // omit ambiguous chars
  let code = "TRN-";
  for (let i = 0; i < 6; i++) {
    code += chars[Math.floor(Math.random() * chars.length)];
  }
  return code;
}

async function main() {
  console.log("🌱 Seeding database...");

  // Wipe existing data so seed is idempotent
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.review.deleteMany();
  await prisma.product.deleteMany();
  await prisma.brand.deleteMany();
  await prisma.trainer.deleteMany();

  const products = loadProducts();
  console.log(`  Loaded ${products.length} products from data/products/`);

  // 1. Create unique brands
  const uniqueBrandNames = Array.from(new Set(products.map((p) => p.brand)));
  const brandRecords = await Promise.all(
    uniqueBrandNames.map((name) =>
      prisma.brand.create({ data: { name } })
    )
  );
  const brandIdByName = new Map(brandRecords.map((b) => [b.name, b.id]));
  console.log(`  Created ${brandRecords.length} brands: ${uniqueBrandNames.join(", ")}`);

  // 2. Create products
  for (const p of products) {
    const brandId = brandIdByName.get(p.brand);
    if (!brandId) throw new Error(`Brand not found: ${p.brand}`);
    await prisma.product.create({
      data: {
        slug: p.slug,
        name: p.name,
        description: p.description,
        category: p.category,
        brandId,
        priceMrp: p.priceMrp,
        priceSale: p.priceSale,
        stock: p.stock,
        rating: p.rating,
        reviewCount: p.reviewCount,
        isBestseller: p.isBestseller,
        isSellingFast: p.isSellingFast,
        proteinPerServing: p.proteinPerServing,
        servingsPerContainer: p.servingsPerContainer,
        dosePerServing: p.dosePerServing,
        capsules: p.capsules,
        tablets: p.tablets,
        caloriesPerServing: p.caloriesPerServing,
      },
    });
  }
  console.log(`  Created ${products.length} products`);

  // 3. Create 3 sample trainers with auto codes
  const trainers = [
    { name: "Rahul Sharma", phone: "+91 98765 43210", email: "rahul@gym.local" },
    { name: "Priya Verma", phone: "+91 98765 43211", email: "priya@gym.local" },
    { name: "Amit Patel", phone: "+91 98765 43212", email: "amit@gym.local" },
  ];
  for (const t of trainers) {
    await prisma.trainer.create({
      data: { ...t, uniqueCode: generateTrainerCode() },
    });
  }
  const allTrainers = await prisma.trainer.findMany();
  console.log(
    `  Created ${allTrainers.length} trainers: ` +
      allTrainers.map((t) => `${t.name} (${t.uniqueCode})`).join(", ")
  );

  console.log("✅ Seed complete");
}

main()
  .catch((e) => {
    console.error("❌ Seed failed", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
